# Pandas

In [1]:
import pandas as pd

pd.__version__

'3.0.6'

In [ ]:
ser1 = pd.Series([100, 80, 92, 99, 89], index=["Alice", "Bob", "Charlie", "David", "Alice"])
ser1

Alice      100
Bob         80
Charlie     92
David       99
Alice       89
dtype: int64

In [3]:
ser1.index

Index(['Alice', 'Bob', 'Charlie', 'David', 'Alice'], dtype='str')

In [4]:
'Alice' in ser1

True

In [7]:
ser1.get('Alice', 200)

Alice    100
Alice     89
dtype: int64

In [11]:
print(ser1.ndim)
print(ser1.shape)
print(ser1.size)
print(ser1.dtype)

1
(5,)
5
int64

In [ ]:
i1 = pd.Index([1,2,3,4,5])
i2 = pd.Index([5,6,7,8,9])

print(i1 | i2)
print(i1 & i2)

Index([5, 6, 7, 12, 13], dtype='int64')
Index([1, 2, 3, 0, 1], dtype='int64')

0

## 接下来，跟着 GPT 给的内容进行练习

In [186]:
import pandas as pd

df = pd.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie", "David", "Alice"],
        "age": [25, 30, 28, None, 25],
        "score": [90, 85, 95, 70, 90],
        "city": ["Shanghai", "Beijing", "Shanghai", "Shenzhen", "Shanghai"],
        "category": ["A", "B", "A", "B", "A"],
    }
)

print(df)

      name   age  score      city category
0    Alice  25.0     90  Shanghai        A
1      Bob  30.0     85   Beijing        B
2  Charlie  28.0     95  Shanghai        A
3    David   NaN     70  Shenzhen        B
4    Alice  25.0     90  Shanghai        A

### Series 练习

练习目标：
- 分别打印行数、列数、列名和数据类型。
- 观察 df["score"] 与 df[["score"]] 的区别。
- 使用 describe() 查看平均值、标准差、最小值和最大值。

In [49]:
row, col = df.shape


print(f'行数 row = {row}')
print(f'列数 col = {col}')
print(df.columns)
print(df.dtypes)

print('=' * 20)
print(df["score"], type(df['score'])) # 返回的是一个 Series
print(df[['score']], type(df[['score']])) # 返回一个 DataFrame

行数 row = 5
列数 col = 5
Index(['name', 'age', 'score', 'city', 'category'], dtype='str')
name            str
age         float64
score         int64
city            str
category        str
dtype: object
====================
0    90
1    85
2    95
3    70
4    90
Name: score, dtype: int64 <class 'pandas.Series'>
   score
0     90
1     85
2     95
3     70
4     90 <class 'pandas.DataFrame'>

In [ ]:
des = df.describe()
print(des, type(des))


des['age']['mean']

            age      score
count   4.00000   5.000000
mean   27.00000  86.000000
std     2.44949   9.617692
min    25.00000  70.000000
25%    25.00000  85.000000
50%    26.50000  90.000000
75%    28.50000  90.000000
max    30.00000  95.000000 <class 'pandas.DataFrame'>

np.float64(27.0)

In [129]:
print(df)
# 1. 获取 Alice 的分数
print(df[df["name"] == "Alice"].loc[0]["score"])
print(df[df["name"] == "Alice"]['score'])
print(df.loc[df['name'] == 'Alice', 'score'])

      name   age  score      city category
0    Alice  25.0     90  Shanghai        A
1      Bob  30.0     85   Beijing        B
2  Charlie  28.0     95  Shanghai        A
3    David   NaN     70  Shenzhen        B
4    Alice  25.0     90  Shanghai        A
90
0    90
4    90
Name: score, dtype: int64
0    90
4    90
Name: score, dtype: int64

In [130]:
# 2. 获取第 2 个元素
df.iloc[1]

name            Bob
age            30.0
score            85
city        Beijing
category          B
Name: 1, dtype: object

In [ ]:
# 3. 找出分数大于等于 90 的元素
df[df["score"] >= 90]

In [ ]:
# 4. 找出分数在 80 到 95 之间的元素
df[df["score"].between(80, 95)]

df[(df['score'] > 80) & (df['score']<95)]

    name   age  score      city category
0  Alice  25.0     90  Shanghai        A
1    Bob  30.0     85   Beijing        B
4  Alice  25.0     90  Shanghai        A

In [132]:
# 5. 获取分数最高的 3 个元素
df.nlargest(3, columns="score")

      name   age  score      city category
2  Charlie  28.0     95  Shanghai        A
0    Alice  25.0     90  Shanghai        A
4    Alice  25.0     90  Shanghai        A

In [134]:
# 6. 统计每种分数出现的次数
df["score"].value_counts()

score
90    2
85    1
95    1
70    1
Name: count, dtype: int64

### dataframe 条件筛选和排序

In [138]:
# 1. 筛选年龄大于 25 岁的人
df[df['age'] > 25]

      name   age  score      city category
1      Bob  30.0     85   Beijing        B
2  Charlie  28.0     95  Shanghai        A

In [ ]:
# 2. 筛选城市为 Shanghai 且分数 >= 90 的人
df[(df['city'] == 'Shanghai') & (df['score'] >= 90)]

      name   age  score      city category
0    Alice  25.0     90  Shanghai        A
2  Charlie  28.0     95  Shanghai        A
4    Alice  25.0     90  Shanghai        A

In [165]:
# 3. 筛选分数属于 85、90、95 的记录
df[(df["score"] == 85) | (df["score"] == 90) | (df["score"] == 95)]

# 写法 2

df[df['score'].isin([85,90,95])]

      name   age  score      city category
0    Alice  25.0     90  Shanghai        A
1      Bob  30.0     85   Beijing        B
2  Charlie  28.0     95  Shanghai        A
4    Alice  25.0     90  Shanghai        A

In [152]:
# 4. 按分数从高到低排序
df.sort_values('score', ascending=False)

      name   age  score      city category
2  Charlie  28.0     95  Shanghai        A
0    Alice  25.0     90  Shanghai        A
4    Alice  25.0     90  Shanghai        A
1      Bob  30.0     85   Beijing        B
3    David   NaN     70  Shenzhen        B

In [154]:
# 5. 找出分数最高的 3 条记录
df.nlargest(3, 'score')

      name   age  score      city category
2  Charlie  28.0     95  Shanghai        A
0    Alice  25.0     90  Shanghai        A
4    Alice  25.0     90  Shanghai        A

In [182]:
# 6. 按年龄升序、分数降序进行多列排序
df_1 = pd.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie", "David", "Ellis"],
        "age": [25, 30, 28, None, 25],
        "score": [90, 85, 95, 70, 92],
        "city": ["Shanghai", "Beijing", "Shanghai", "Shenzhen", "Shanghai"],
        "category": ["A", "B", "A", "B", "A"],
    }
)
df_1.sort_values(["age", "score"], ascending=[True, False])

      name   age  score      city category
4    Ellis  25.0     92  Shanghai        A
0    Alice  25.0     90  Shanghai        A
2  Charlie  28.0     95  Shanghai        A
1      Bob  30.0     85   Beijing        B
3    David   NaN     70  Shenzhen        B

### 修改 dataframe 
```python
# 1. 新增一列 passed，分数 >= 60 为 True

# 2. 新增一列 score_plus_5，分数增加 5 分

# 3. 将 score 列重命名为 points

# 4. 删除 category 列

# 5. 将 age 转换为合适的数据类型

# 6. 修改某一行某个单元格的值
```

In [167]:
# 1. 新增一列 passed，分数 >= 80 为 True
df['passed'] = df['score'] >= 80
df

      name   age  score      city category  passed
0    Alice  25.0     90  Shanghai        A    True
1      Bob  30.0     85   Beijing        B    True
2  Charlie  28.0     95  Shanghai        A    True
3    David   NaN     70  Shenzhen        B   False
4    Alice  25.0     90  Shanghai        A    True

In [169]:
# 2. 新增一列 score_plus_5，分数增加 5 分
df['score_plus_5'] = df['score'] + 5
df

      name   age  score      city category  passed  score_plus_5
0    Alice  25.0     90  Shanghai        A    True            95
1      Bob  30.0     85   Beijing        B    True            90
2  Charlie  28.0     95  Shanghai        A    True           100
3    David   NaN     70  Shenzhen        B   False            75
4    Alice  25.0     90  Shanghai        A    True            95

In [ ]:
# 3. 将 score 列重命名为 points
df.rename(columns={"score": "points"}, inplace=[True])
df

      name   age  points      city category  passed  score_plus_5
0    Alice  25.0      90  Shanghai        A    True            95
1      Bob  30.0      85   Beijing        B    True            90
2  Charlie  28.0      95  Shanghai        A    True           100
3    David   NaN      70  Shenzhen        B   False            75
4    Alice  25.0      90  Shanghai        A    True            95

In [188]:
# 4. 删除 category 列
df.drop(columns=['category'])

      name   age  score      city
0    Alice  25.0     90  Shanghai
1      Bob  30.0     85   Beijing
2  Charlie  28.0     95  Shanghai
3    David   NaN     70  Shenzhen
4    Alice  25.0     90  Shanghai

In [255]:
# 5. 将 age 转换为合适的数据类型
df['age'] = df["age"].astype("Int64")
df

      name   age  score      city category
0    Alice    25     90  Shanghai        A
1      Bob    30     85   Beijing        B
2  Charlie    28     95  Shanghai        A
3    David  <NA>     70  Shenzhen        B
4    Alice    25     90  Shanghai        A

In [ ]:
# 6. 修改某一行某个单元格的值
df1 = df.copy()
df1.loc[3, 'age'] = 24
df1
# df

      name   age  score      city category
0    Alice  25.0     90  Shanghai        A
1      Bob  30.0     85   Beijing        B
2  Charlie  28.0     95  Shanghai        A
3    David  24.0     70  Shenzhen        B
4    Alice  25.0     90  Shanghai        A